language: swift
osx_image: xcode8.3
script:
- xcodebuild -workspace Kommander.xcworkspace -scheme Major -destination "platform=iOS
  Simulator,name=iPhone 7,OS=10.3.1" -configuration Debug -enableCodeCoverage YES clean
  build test
after_success:
- bash <(curl -s https://codecov.io/bash)
- sh Scripts/gnscharts.sh Kommander Major IG27 none Testing