language: objective-c
xcode_project: Kommander.xcodeproj
xcode_scheme: Kommander

osx_image: xcode7.3
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild -scheme Kommander -enableCodeCoverage YES clean build test
